global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitoring'


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093


# A list of scrape configurations.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'localhost:9090'

  - dns_sd_configs:
    - names:
      - tasks.cadvisor
      port: 8080
      type: A
    job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 192.168.50.53:8080
      - 192.168.50.61:8080
      - 192.168.50.62:8080
      - 192.168.50.52:8080
      - 192.168.50.54:8080

  - dns_sd_configs:
    - names:
      - tasks.node-exporter
      port: 9100
      type: A
    job_name: node-exporter
    scrape_interval: 5s
    static_configs:
    - targets:
      - 192.168.50.53:9100
      - 192.168.50.61:9100
      - 192.168.50.62:9100
      - 192.168.50.52:9100
      - 192.168.50.54:9100

